[tool.poetry]
name = "pamo-nonebot-ff14Tools"
version = "1.0"
description = "a simple ff14's tools"
authors = ["opaup <opaup5259@gmail.com>"]
readme = "README.md"
packages = [
	{ include = "." },
]
[tool.poetry.dependencies]
python = "^3.8"

